on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Preview
        run: pnpm preview

        # Run a build step here if your project requires
        # - name: Cloudflare Pages GitHub Action
        # uses: cloudflare/pages-action@v1.5.0
        # with:
        #   apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        #   accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        #   projectName: test-cf-action
        #   directory: ./
        #   # Optional: Enable this if you want to have GitHub Deployments triggered
        #   gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        #   # Optional: Switch what branch you are publishing to.
        #   # By default this will be the branch which triggered this workflow
        #   branch: action
        #   # Optional: Change the working directory
        #   workingDirectory: ./dist
        #   # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
        #   wranglerVersion: "3"
